title = "tech.structionsite"
base_url = "https://tech.structionsite.com/"
compile_sass = false
build_search_index = false

taxonomies = [
    {name = "tags"}, 
    {name = "authors"}, 
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"


[extra]
favicon = "static/favicon.png"
